# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-TokeParser-Simple
version:      3.13
version_from: lib/HTML/TokeParser/Simple.pm
installdirs:  site
requires:
    HTML::Parser:                  3.25
    HTML::TokeParser:              2.24
    Sub::Override:                 
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
